app_homepage:
    path:     /
    defaults: { _controller: appBundle:Default:index }

app_hello:
    path:     /hello/{name}
    defaults: { _controller: appBundle:Default:hello }

app_bookmark:
    path:     /bookmark
    defaults: { _controller: appBundle:Bookmark:index }

app_bookmark2:
    path:     /bookmark/{id}
    defaults: { _controller: appBundle:Bookmark:detal }