services:
#    app.example:
#        class: appBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
#    app/config/services.yml
     app.repository.bookmark:
         class: appBundle\Repository\BookmarkRepository